spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  application: springcloud-config-coding-dev
  
---
spring: 
  profiles: test
  application: springcloud-config-coding-test
