spring:
  profiles:
    active: dev
---
server:
  port: 8201
spring:
  profiles: dev
  application: springcloud-config-client-dev
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  
---
server:
  port: 8202
spring:
  profiles: test
  application: springcloud-config-client-test
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
