server:
  port: 3344
spring:
  application:
    name: springcloud-config
  # 配置git的绑定
  cloud:
    config:
      server:
        git:  # 细节： uri， 不是url
          uri: https://gitee.com/kuangstudy/springcloud-config.git