spring:
  profiles:
    active: dev

---
server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.coding.springcloud.pojo
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml
spring:
  profiles: dev
  application:
    name: springcloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/springcloud01
    username: root
    password: pass
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: provider8001

info:
  app.name: jingProviding8001
  company.name: Jing
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}

---
server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.coding.springcloud.pojo
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml
spring:
  profiles: test
  application:
    name: springcloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/springcloud03
    username: root
    password: pass
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: provider8001

info:
  app.name: jingProviding8001
  company.name: Jing
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}